container: aozora0000/jenkins-ci-php:5.4
steps:
    - name: composerインストール
      code: composer update --prefer-dist
    - name: PHPUNIT起動
      code: phpunit
notify:
    - service: idobata
      token: $IDOBATA_TOKEN
